### ISSUE TITLE
Issue with the ActivityDataset update?

### ISSUE THREAD

**Issue by RomainBes** [brightway-lca/brightway25#3]
I tried to update the activity dataset attributes, but it seems there is a bug, or something I'm doing wrong.

After importing : from bw2data.backends import ActivityDataset as AD

I tried to update the activity name as in this notebook by executing the command:
AD.update(name="Wow, this is some car!").where(AD.name == 'Combustion car').execute()

The change appears to be partially effective because, using the get_node() function, I can get the activity with its new name, but the output still has the old name...

![image](https://user-images.githubusercontent.com/23096554/203300872-8030b5c0-90cb-45e4-a0db-6cd8777f8515.png)

Thanks for your feedback on this issue,

Romain

PS: The same behavior happens for the ExchangeDataset.

The brightway version is:
bw-migrations 0.2
bw-processing 0.8.2
bw2analyzer 0.11.4
bw2calc 2.0.dev12
bw2data 4.0.dev18
bw2io 0.9.dev11
bw2parameters 0.7

**Comment by RomainBes** [comment]
The brightway version is: 
bw-migrations        0.2
bw-processing        0.8.2
bw2analyzer          0.11.4
bw2calc              2.0.dev12
bw2data              4.0.dev18
bw2io                0.9.dev11
bw2parameters        0.7

**Comment by cmutel** [comment]
Yes, this is a bug which is fixed in git but the fix is not yet released. But thanks, it is good to have a reminder!

**Comment by RomainBes** [comment]
Ok, I'll close the issue and wait for the next release!

**Comment by cmutel** [comment]
I am working on it, need to put out fires before rebuilding the structure...
